# The URL the site will be built for
base_url = "https://pengyi.me"
defaultContentLanguage = "zh"
languageCode = "zh-CN"
title = "一哥黑板报"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = "github"  # 保留中文锚点
      
[params]
  themeColor = "#3C91E6"
  homeInfoMode = "PostList"

# 启用中文拼音排序（如果需要）
[languages.zh]
  weight = 1
  languageName = "中文"
  contentDir = "content/zh"

