site_name: 一哥黑板报
site_url: https://www.pengyi.me
site_author: 彭一

theme:
  name: null
  custom_dir: neotale
  # name: material
  # favicon: /assets/images/favicon.png
  # logo: /assets/images/logo_450x300.png
  # features: 
  # palette:
  #   - scheme: py


markdown_extensions:
  - meta

nav:
  - Tech: techs/index.md
  - Life: lifes/index.md
  - About: about.md
  
copyright:  Copyright © 2008 <a href="https://github.com/RyanPoy/blog">彭一</a> Rights Reserved
