site_name: 一哥黑板报
site_url: https://www.pengyi.me
site_author: 彭一
site_copyright:  
  - Copyright © <time datetime="2008-07-21 00:00:00 +0000">2008</time> <a href="https://github.com/RyanPoy/blog">彭一</a> Rights Reserved
  - Made with <a href="https://github.com/mkdocs/mkdocs/">mkdocs</a> using the <a href="https://github.com/RyanPoy/mkdocs-tale/">Tale</a> theme.

theme:
  name: tale

markdown_extensions:
  - meta
  
nav:
  - Tech: techs/index.md
  - Life: lifes/index.md
  - Tutorial: tutorials/index.md
  - About: about.md

plugins:
  - tale
