site_name: 一哥黑板报

theme:
  name: material
  favicon: /asserts/images/favicon.png
  logo: /asserts/images/logo_450x300.png
  features: 
    - navigation.instant      # 点击链接时使用 XHR 即时加载页面
    - navigation.tracking     # 页面滚动时自动更新 URL 中的 hash
    - navigation.tabs         # 把顶层导航展示为页面顶部的标签页
    - navigation.tabs.sticky  # 让标签栏在滚动中固定在顶部 (sticky)
    # - navigation.sections     # 在标签下方显示内容分组
    # - navigation.expand       # 展开所有子级导航
    # - navigation.indexes      # 将 section 中的 index.md 设置为默认入口
    - navigation.top          # 显示“回到顶部”按钮
    # - navigation.footer       # 启用页面底部的上一篇/下一篇链接
    - search.highlight


nav: [
  index.md,
  about.md,
  lifes/index.md,
  techs/index.md,
]
copyright:  Copyright © 2008 <a href="https://github.com/RyanPoy/blog">彭一</a> Rights Reserved
