site_name: 一哥黑板报
site_url: https://www.pengyi.me
site_author: 彭一

theme:
  name: null
  custom_dir: neotale
  # name: material
  # favicon: /asserts/images/favicon.png
  # logo: /asserts/images/logo_450x300.png
  # features: 
  # palette:
  #   - scheme: py

extra_css:
  - asserts/stylesheets/extra.css

nav:
  - Home: index.md
  - Tech: lifes/index.md
  - Life: techs/index.md
  - About: about.md
  
copyright:  Copyright © 2008 <a href="https://github.com/RyanPoy/blog">彭一</a> Rights Reserved
