site_name: 一哥黑板报
site_url: https://www.pengyi.me
site_author: 彭一
site_copyright:  
  - Copyright © <time datetime="2008-07-21 00:00:00 +0000">2008</time> <a href="https://github.com/RyanPoy/blog">彭一</a> Rights Reserved
  - Made with <a href="https://github.com/mkdocs/mkdocs/">mkdocs</a> using the <a href="https://github.com/RyanPoy/mkdocs-tale/">Tale</a> theme.

theme:
  name: tale

markdown_extensions:
  - meta
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - toc:
      permalink: true

nav:
  - Tech: techs/index.md
  - Life: lifes/index.md
  - Tutorial: tutorials/index.md
  - About: about.md

plugins:
  - tale

### Optional: Enable GitHub Discussion Comments via Giscus
# To enable Giscus comment integration, add the following to your `mkdocs.yml`:
extra:
  giscus:
    repo: "YOUR REPO"
    repo_id: "YOUR REPO ID"
    category: "Comments"
    category_id: "YOUR CATEGORY ID"
    mapping: pathname
    theme: light
    reactions_enabled: '1'
    input-position: 'bottom'
