# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('show', models.BooleanField(db_index=True, default=True, verbose_name='是否发布')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='标题')),
                ('keywords', models.CharField(default='', editable=False, max_length=255, null=True, verbose_name='关键词')),
                ('content', models.TextField(default='', verbose_name='MarkDown内容')),
                ('view_number', models.IntegerField(default=0, verbose_name='浏览次数')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('show', models.BooleanField(db_index=True, default=True, verbose_name='是否发布')),
                ('pic', models.ImageField(upload_to='', verbose_name='图片')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('show', models.BooleanField(db_index=True, default=True, verbose_name='是否发布')),
                ('title', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='标题')),
                ('keywords', models.CharField(default='', editable=False, max_length=255, null=True, verbose_name='关键词')),
                ('content', models.TextField(default='', verbose_name='MarkDown内容')),
                ('seq', models.IntegerField(default=0, verbose_name='排序')),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '单页面',
                'verbose_name_plural': '单页面',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('show', models.BooleanField(db_index=True, default=True, verbose_name='是否发布')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='名字')),
                ('article_number', models.IntegerField(default=0, verbose_name='文章数量')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='app.Tag', verbose_name='标签'),
        ),
    ]
