# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('show', models.BooleanField(db_index=True, default=True, verbose_name='是否发布')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('url', models.URLField(max_length=255, verbose_name='链接地址')),
                ('seq', models.IntegerField(db_index=True, default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '链接',
                'verbose_name_plural': '链接',
                'ordering': ['seq'],
            },
        ),
        migrations.AlterField(
            model_name='page',
            name='seq',
            field=models.IntegerField(db_index=True, default=0, verbose_name='排序'),
        ),
    ]
