# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170817_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='uri',
            field=models.CharField(db_index=True, default='', max_length=255, verbose_name='跳转地址'),
            preserve_default=False,
        ),
    ]
