# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170818_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('show', models.BooleanField(db_index=True, default=True, verbose_name='是否发布')),
                ('name', models.CharField(max_length=255, verbose_name='名称')),
                ('seq', models.IntegerField(db_index=True, default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '系列',
                'verbose_name_plural': '系列',
                'ordering': ['seq'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='series',
            field=models.ManyToManyField(to='app.Series', verbose_name='系列'),
        ),
    ]
