# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170822_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='series',
            field=models.ManyToManyField(blank=True, null=True, to='app.Series', verbose_name='系列'),
        ),
    ]
