# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170822_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='series2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series_id', to='app.Series', verbose_name='系列'),
        ),
    ]
