# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_article_series'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='series2',
            new_name='series',
        ),
    ]
