# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20171024_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='uri',
            field=models.CharField(db_index=True, max_length=255, verbose_name='跳转地址'),
        ),
    ]
