# Generated by Django 2.0.4 on 2018-04-19 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20171024_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('show', models.BooleanField(db_index=True, default=True, verbose_name='是否发布')),
                ('signinname', models.CharField(db_index=True, max_length=255, verbose_name='登录名')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(db_index=True, max_length=255, verbose_name='密码')),
                ('role', models.IntegerField(db_index=True, default=100, verbose_name='权限')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, related_name='series_id', to='app.Series', verbose_name='系列'),
        ),
        migrations.AlterField(
            model_name='page',
            name='author',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
    ]
