# Generated by Django 2.0.4 on 2018-04-19 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180419_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='page',
            name='author',
        ),
    ]
